apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- update-yahoo-api.yaml
namespace: influx-apps
images:
- newName: bitfolio/update-yahoo-finance
  newTag: v0.0.3
- name: update-yahoo-finance
  newName: bitfolio/update-yahoo-finance
  newTag: v1.2
